### ISSUE TITLE
Cannot access http://localhost:8000/ using ufront server

### ISSUE THREAD

**Issue by tiagolr** [ufront/hello#1]
If i use `ufront server` on projectDir, on the terminal it says:

Starting Neko Server on XXXX-PC:2987

when i try to access http://localhost:8000/ i get : Error code 102 (net::ERR_CONNECTION_REFUSED) 
(also tried port 2987)

However if i use 

```
nekotools server -rewrite -p 8000 -h localhost -d ./ 
```

from projectDir/www it works fine and i can view all pages.

Using windows 7 64-bit

**Comment by IOrlandoni** [comment]
[https://localhosts.mobi/:8000](Address: https://localhosts.mobi/:8000) Connect the 8000. port from web browser.
