### ISSUE TITLE
BytesData errors with 3.2.1

### ISSUE THREAD

**Issue by axelhuizinga** [ufront/hello#15]
solved - looks like my std lib has been messed up
but now I have not been able to adapt the RewriteBase to make it work on localhost with php except keeping it at / and moving the content of www to my DocumentRoot - There I can access http://localhost/signup/newname/ and get the signup form - but sending it fails with:

Remoting API ufront.auth.api.EasyAuthApi.getCurrentUser() not found: Unable to access ufront.auth.api.EasyAuthApi.getCurrentUser - API Not Found (Invalid path ufront.auth.api.EasyAuthApi.getCurrentUser). See {}

Details
RApiNotFound(ufront.auth.api.EasyAuthApi.getCurrentUser(),Unable to access ufront.auth.api.EasyAuthApi.getCurrentUser - API Not Found (Invalid path ufront.auth.api.EasyAuthApi.getCurrentUser). See {})

**Comment by kevinresol** [comment]
Did you specify your remote api context?

e.g.
```haxe
ufrontApp = new UfrontApplication({
	indexController: HomeController,
	remotingApi:api.ApiContext, // <= this line
});
```

**Comment by axelhuizinga** [comment]
no - I tried with the code like it is in the source on github 
:/ufront/hello/blob/master/HelloWorld.hx

class HelloWorld {
     static function main() {
         #if server
             // Initialise the app on the server and execute the request.
             var ufApp = new UfrontApplication({
                 indexController: HelloWorldController,
                 defaultLayout: "layout.html"
             });
             #if (php || neko)
                 ufApp.executeRequest();
             #elseif nodejs
                 ufApp.listen();
             #end
         #elseif client
             // Initialise the app on the client and respond to 
"pushstate" requests as a single-page-app.
             var clientApp = new ClientJsApplication({
                 indexController: HelloWorldController,
                 defaultLayout: "layout.html"
             });
             clientApp.listen();
         #end
     }
}

Am 11.03.2016 um 11:59 schrieb Kevin Leung:

**Comment by JustDoInGmYpArT** [comment]
u guys know who hello world belongs to
