### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by ConfidantCommunications** [ufront/hello#8]
I am attempting to run the `ufront task` command and getting this error:

> Called from ? line 1
> Called from Tasks.hx line 22
> Called from /usr/lib/haxe/std/neko/_std/sys/db/Mysql.hx line 203
> Uncaught exception - mysql.c(508) : Failed to connect to mysql server : Failed to connect on host 'localhost'

I have set up the database/user/password of ufhelloworld using PHPMyAdmin on MAMP. Restarted the servers. Tried changing mysql.json to my normal "root" user that I use, still the error.

Is this perhaps a Haxe bug?

**Comment by jasononeil** [comment]
Just to check, you are recompiling after editing the JSON file?

As a simple test of if it's a problem in ufront, your code, or Haxe, you could try the most basic:

```haxe
class Test {
  static function main() {
    sys.db.Manager.cnx = sys.db.Mysql.connect({ user: ..., port: ...., pass: ..., host: ..., database: ... });
  }
}
```

If that test works, then your MySQL (and Haxe) is working correctly.  If not it would appear Ufront is sending the wrong connection details somewhere, and I'll look into it.

Let me know how it goes

**Comment by ConfidantCommunications** [comment]
Yes I tried doing `ufront build` after changing the JSON to the root user and still `ufront task` displayed the same error message.

I have now made a Test class using your code example. That worked fine and displayed a blank page when the login was correct, and displayed connection errors when I intentionally used the wrong password.

**Comment by ConfidantCommunications** [comment]
Any further ideas? :)

**Comment by ConfidantCommunications** [comment]
The MAMP default settings use a Unix socket to connect to the database, and I discovered that neko on Mac is not able to connect via a socket. I had to visit the MySQL tab in MAMP and checked "Allow network access to MySQL" and click save. That resolved this particular problem.
